### ISSUE TITLE
Strip ulog completely from production codes with Webpack/Babel

### ISSUE THREAD

**Issue by guopengliang** [Download/ulog#17]
Just wondering what is the recommended approach to strip the ulog dependency and related logging codes completely from production codes? Like for instance, with Babel there's the `babel-plugin-transform-remove-console` to remove all `console.*` codes, or with Webpack the `strip-loader` to do so.

**Comment by Download** [comment]
The way to do this is with the [Webpack DefinePlugin](https://webpack.js.org/plugins/define-plugin/)

Basically, in production builds, you use the define plugin to set `process.env.NODE_ENV` to `'production'`.
Then, in your code, you check this constant:

```js
if (process.env.NODE_ENV != 'production') {
  var log = require('ulog')('my-module')
}

// ...

if (process.env.NODE_ENV != 'production') {
  log.info('This log message will be stripped from production builds')
}
```

The reason this works is that Webpack will actually replace all instances of `process.env.NODE_ENV` with the constant you specified at compile time, turning the above code into:

```js
if ('production' != 'production') {
  var log = require('ulog')('my-module')
}

// ...

if ('production' != 'production') {
  log.info('This log message will be stripped from production builds')
}
```

UglifyJS is smart enough to realize that the condition in the `if` is always `false` and so the code inside the `if` block is dead code. So it strips that code away, just as we want it.

The code above uses the fact that `var` variables are hoisted; even though the `log` variable is defined *inside* an `if` block, after is has been defined it is hoisted by the interpreter to the function/module scope so it can actually be used outside the if. Some consider this ugly, but in this case it is a simple solution.

The code above also uses the fact that `require` is completely dynamic. If `process.env.NODE_ENV` is set to `'production'`, the call to `require` is never executed so the `ulog` module code is also no bundled.

I am sure it is also possible to do this with ES6, but it is a little bit more complicated since `import` must be static and `let` and `const` are not hoisted.

When you do go this route, I actually recommend you leave at least some log messages in the production build as being able to enable logging on the production build is actually a very powerful feature imho and `ulog` has been optimized for this scenario. You could import the `ulog` module and then surround all messages logged at levels `LOG` and `DEBUG` with the check for `NODE_ENV` for example, leaving `INFO` / `WARN` / `ERROR` level messages in there.
