### ISSUE TITLE
Is it possible to use full/kurly and still have working call stack from browser ?

### ISSUE THREAD

**Issue by Oksy-d** [Download/ulog#38]
Currently as soon as I use kurly stuff, it shows "structured.js" as the caller of the console.log

![ulog](https://user-images.githubusercontent.com/73394632/102108031-b15ed080-3e32-11eb-9a1b-663685a2001b.png)

My config :
`localStorage.setItem('log', 'debug');`
`localStorage.setItem('log_format', '{date}{time}{lvl}{name}{message}{perf};clientUtil=simple;kurly=none');`

My project is running [Vuetify](https://vuetifyjs.com/en/)

**Comment by Download** [comment]
Yes you are right. All kurly formatters are dynamic formatters atm.

I am actually working on the formatters at the moment and I'm trying to improve the usefulness of the static formatters. I think I can make them a whole lot more useful than they are now. But I don't see a way of making kurly formatters static. So I'm actually thinking about removing kurly altogether though I am not sure yet. Watch the next beta as it should have much more in terms of formatters *(oh and don't tell anyone but I'm adding colors 😉 )*

**Comment by Download** [comment]
Ok so I have a small update on this.
Yes, it *will* be possible to use full/kurly with a working call stack.
I am preparing a new v2 release of kurly to support that.
It turns out that I can make a formatter that detects whether you are only using 'static formatters' (see Kurly v2 docs for more info) and if so, creates a static pipeline that does not mess up your call stack. Of course if you need access to the message, a static formatter will not do. But I found there is **a lot** that you can do with static formatters alone!
In the next beta I am trying to give you:

* Edit the format string just like in beta 10 with Kurly
* Kurly braces optional for shorter/simpler format strings
* If all formatters used are static, the call stack remains untouced
* If you use dynamic formatters, it will detect this automatically and switch to a dynamic formatting pipeline
* Colors!!

I had it all working great but I as completely sidestepping Kurly because it did not support te concept of static formatters. So I did what a good dev does and I refactored Kurly. Check out Kurly v2 and it has all new features for optional kurly braces and static formatters!

The next step is refactoring ulog v2 beta 12 to not sidestep kurly but use the new features introduced in kurly v2, So atm nothing is working anymore as I am refactoring ulog again to not reinvent the weel but rely on kurly. So it will take a bit more time still but it is coming! And ulog will be the only logger I know that is able to do this so I am very proud. Will comment here again when I released it. So a bit more patience please but it is coming.

**Comment by Download** [comment]
@Oksy-d 
Please check out the latest beta. It supports formatting with kurly, nicer format strings and preserving the call stack as long as you only use static formats. Oh I also added alignment (nicely lining up all messages in browsers and node) and colors!

Let me know what you think and feel free to re-open or open new issues with your findings.
