### ISSUE TITLE
Backtrace in Regex makes 2.0.0-beta.10 incompatible with Safari (iPhone 11 Pro Max)

### ISSUE THREAD

**Issue by kieranbenton** [Download/ulog#40]
Causes:

![image](https://user-images.githubusercontent.com/39090/103353267-58cd3b80-4aa0-11eb-9ece-2c07fe9abfb9.png)

I think I've traced it to ulog, specifically https://github.com/Download/ulog/blob/c9aca9010b8daf25ce580fbb1da86d02fd44079f/mods/options/index.js#L70

**Comment by Download** [comment]
Yes you are right. I reproduced this in Internet Explorer 11 as well. It's got to do with the lookbehind (or ahead?) in `split(/(?<!\\);/)`. I'm working on it right now. Should be fixed in the next beta.

Thank you for reporting this!

**Comment by kieranbenton** [comment]
Any luck with this? Do you need a hand?

**Comment by Download** [comment]
What this regex does, is find semicolons that are *not* preceded by a backslash. The idea was that you can escape semicolons that way. But it is a bit of a fix for a theoretical issue. You don;t need semicolons in any of the config settings as of yet. So I just removed this and changed it to `items.split(';')`. It's more that I am (*again...*) refactoring the formatting which is why the next beta is taking some time. Let me see if I can quickly throw out a new beta with just this one issue fixed for you ❤️
