### ISSUE TITLE
Fail to build on windows

### ISSUE THREAD

**Issue by johnd0e** [Download/ulog#41]
```log
npm install

> ulog@2.0.0-beta.10 prepare C:\D\repos\ulog
> npm run test -S && npm run clean -S && npm run build -S


> ulog@2.0.0-beta.10 test C:\D\repos\ulog
> nyc tape test.js 2>&1 | tap-nirvana


    'sh' is not recognized as an internal or external command,
    operable program or batch file.
    ----------|---------|----------|---------|---------|-------------------
    File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
    ----------|---------|----------|---------|---------|-------------------
    All files |       0 |        0 |       0 |       0 |
    ----------|---------|----------|---------|---------|-------------------
```

**Comment by Download** [comment]
Mmm that's weird as I'm on Windows myself... Though I have Git for Windows installed, which installs some Unix tools as well, so maybe that's why it's working for me. I am not using `sh` directly anywhere myself so I'm guessing `nyc`, `tape` or `tap-nirvana` is using it somewhere....

Can you maybe try to change the entry in package.json `test` script and remove part(s) of the command to help pinpoint the failure?

E.g. change 
`nyc tape test.js 2>&1 | tap-nirvana` to `tape test.js 2>&1 | tap-nirvana` and `nyc tape test.js 2>&1` and `tape test.js` etc?

In any way I don't think this is a bug in ulog actually, but probably in nyc or tape or tap-nirvana...

**Comment by johnd0e** [comment]
> In any way I don't think this is a bug in ulog actually, but probably in nyc or tape or tap-nirvana...

Definitely that is not `ulog` fault.
`tape test.js 2>&1 | tap-nirvana` -  no error
`nyc tape test.js` - error

**Comment by Download** [comment]
You can try to report it to them if you want, but I hope you are ok if I close this issue here. Please re-open if you feel otherwise.
