### ISSUE TITLE
replacement for ulog.enable(..) method in version 2.

### ISSUE THREAD

**Issue by riceyeh** [Download/ulog#42]
I am moving to ulog version 2. ulong.enable(...) seems gone in version 2. Is there any replacement for it?

**Comment by Download** [comment]
I think it will come back in a mod probably.

For now I wanted to keep things pure a bit more. `ulog` supports getting and setting a wide arrangement of options through 2 methods: `ulog.get()` and `ulog.set()`. You can for example get the current level setting via:

```js
ulog.get('level')
```

this will give you the global setting. You can also get it for just one logger:

```js
ulog.get('level', 'my-logger')
```

You can set it via

```js
ulog.set('level', 'info')
```

The `debug` setting is the one that you are looking for to emulate `ulog.enable`:

```
ulog.set('debug', 'my,loggers,to-enable')
```

`ulog.enable`, `ulog.enabled` and `ulog.disable` are actually special cases of `ulog.get` and `ulog.set`. You can bring them back easily yourself if you want:

```js
ulog.enable = ulog.set.bind(ulog, 'debug')
ulog.enabled = ulog.get.bind(ulog, 'debug')
ulog.disable = ulog.set.bind(ulog, 'debug', '')
```

**Comment by Download** [comment]
Oh and one more thing. May I ask why you are calling `ulog.enable`?

See, one of the reasons I hesitate against adding these methods back in, is that it seems to tell people to use them.
But actually, I think you are better off not using them.

Unless you are building some logger management module, I suggest you don't set the levels of loggers through code. Instead, rely on the configuration options that `ulog` supports to configure your logging via a file, environment variables, localStorage etc. I put *a lot* of effort into making sure that configuring ulog would be easy and work well so that you would never have to mess around with setting log levels manually from code. Your code will be a lot more flexible if it accepts configuration from the outside and `ulog` supports that by default. By calling `ulog.set` you are overriding that configuration mechanism. Please try to use it and tell me whether it's working for you. Mainly, `ulog.set` is there to support overriding settings in memory for situations like in tests etc. But I recommend against using it unless you absolutely need to.

**Comment by Download** [comment]
@riceyeh If you have anything more to add, feel free to re-open

**Comment by Download** [comment]
@riceyeh Try the last beta. I re-enabled the support for `enable`, `enabled` and `disable`.
