### ISSUE TITLE
Can't quite figure out how the drain functionality works

### ISSUE THREAD

**Issue by ifeanyiisitor** [Download/ulog#47]
I'm doing this

```js
import ulog from 'ulog'

export const log = ulog('sample-app')

log.level = log.WARN

ulog.use({
  outputs: {
    drain: {
      log: function (...args) {
        console.log('drain...', args)
      },
    },
  },
})

ulog.set('drain', 'drain')

log('foo...')
log.warn('warn...')

```

In the browser, the call `log('foo')` gets sent to drain. But the call `log.warn('warn...')` doesn't and I don't understand why. How can I set this up so that all log levels get sent to drain?

**Comment by ifeanyiisitor** [comment]
Ok when I pass the query param `?log=none` everything gets sent to drain. So I guess the idea here is that everything except the specified log level get's sent to drain?

**Comment by ifeanyiisitor** [comment]
Ok I think I see whats happening now. Every log type  that is equivalent to the log level and above (in terms of severity) gets logged out and everything else gets drained. If so, my question then is what is the purpose of drain?. I was assuming that if I wanted to send logs to a remote logging service, I would implement that as `drain`. Is that the case? And if so, does it mean then that once the log level is set, every thing that matches it will not be sent to drain? Is that how it's meant to work? I'm new to setting up logging in this manner so apologies if this is all trivial stuff.

**Comment by Download** [comment]
@ifeanyiisitor 
Thanks for your comments. Yes, you are correct in your assumption. Logs get sent to either the `output` channel or to the `drain` channel, depending n whether they are enabled for a certain level or not. So if `enabledFor(level)` returns a truthy value, messages get sent to `output`, otherwise to `drain`.

If you want to send all logging to some service, you can simply set both `output` and `drain` to the same output.

And no this is definitely not trivial stuff. And you may be new to this, but so am I. As you might have noticed, `ulog` v2 is still in beta and I'm still figuring stuff out so any feedback you have is welcome. Thank you for trying `ulog`!

**Comment by Download** [comment]
> log.level = log.WARN

BTW, I advice against this.

> ulog.set('drain', 'drain')

And against this as well  😃 

In general, I say avoid calling `ulog.set` and assigning to properties on the loggers unless you are writing some tests for the loggers or in very specific circumstances (like you are making a UI to control logging with)

Instead of setting values from code, try to use the configuration mechanism. This will give you much cleaner code and you will be able to control all your logging from config. If you do `logger.level = logger.WARN`, you have overridden the level for that logger and it will not respond to config until you remove the override with `logger.level = undefined`.

If you want to change a default, I suggest adding a mod that overrides the default. Suppose you want to set the default value for `level` to `'error'`, you could do this:

```js
ulog.use({
  settings: {
    level: {
      prop: {
        default: 'error'
      }
    }
  }
})
```

You should include this mod in your entry point, before including any code that creates loggers. All loggers created after you added this mod will use your new default.
