### ISSUE TITLE
localStorage variables not working - maybe it's me

### ISSUE THREAD

**Issue by svenmarley** [Download/ulog#50]
I'm new to React, so it might-be/probably-is me.  But, I can't get the localStorage variables to work in my app like they do in the tutorial.  The URL variable **does** work.

I set the Application -> Local Storage -> {local url}
key | value
log | warn; app:re*=all

My loggers are named `app:render`, `app:discover`, `app:updateFile`.

I only want the `app:render` logs to show everything.

It also does not see the log_format localStorage entry either.  So, I'm wondering if this feature just hasn't been completed yet.  Or do I have something set wrong?

I can get to the localStorage.getItem( 'log' ) from inside my app just fine - it returns whatever is in there.

Hopefully, it's something simple I'm missing.

**Comment by Download** [comment]
Also, I'm interested in how you are loading `ulog`. Do you use the script or do you build it yourself with Webpack? And how do you import it? You should import `ulog` in your entrypoint before creating loggers using ``anylogger(name)` so `ulog` can intercept those calls.

**Comment by svenmarley** [comment]
I appreciate your quick feedback.  I got distracted into other _life_ things,_ so that's the reason for the delay.

I don't know what changed, but it is all working great now.  I think it was the realization that the log entries are all lowercase for the loggername, so my App:updateFIle required a log entry like `warn:app:updatef*=all` for it to turn on.  (hell, even in writing this I got it wrong 3 times, typing it like the function is in the code)

Appreciate your response, and the cool library.

**Comment by Download** [comment]
@svenmarley No problem! I'm also sometimes slow to respond. We all have lives right?

About your remark that 'the log entries are all lowercase for the loggername', can you elaborate? Are you saying that if you create a logger with `anylogger('App:updateFile')` you would have to set the key `log` to `warn;app:updatef*=all` for it to work? Because that shouldn't be the case. I expect the casing of loggernames to be preserved and that the names used in the config should use equal casing to the names used in logger creation. So if you create a logger using `anylogger('App:updateFile')` I would expect the `log` key `warn;App:updateF*=all` to work. If this is not the case, can you let me know.

Thanks for trying `ulog` and do come back here if you have any feedback criticism. I appreciate your input!

**Comment by svenmarley** [comment]
I just confirmed that the log= entry is case sensitive.  i.e. 
log=error;search:findb*=debug    = no log messages
log=error;Search:findB*=debug    = log messages

**Comment by reinhard** [comment]
Maybe it's the same problem: since 2.0.0-beta.15 `window.localStorage.setItem('log', 'all')` has no effect. After downgrading to beta.14, debug logs show up again.

**Comment by Download** [comment]
@reinhard Can you try this in the [ulog tutorial](https://ulog.js.org/tutorial) and report if it works there for you? It works as expected for me

**Comment by Download** [comment]
That certainly helps!

Will investigate this. Sorry for the inconvenience but that's why it's still beta... I need this kind of feedback to get everything working right in all contexts. So thank you very much for contributing with reports like this! Will let you know when I reproduce and finally fix this. May take some time though as I just accepted a new job...

**Comment by Download** [comment]
@reinhard Oh, I see you `import 'ulog'` in the entry point.
That *should* work... But as a workaround you might try `import 'ulog/full'`. That should not be needed but it might work.
I have been messing around with this a few betas now. Problem is that it's hard to test before actually publishing...

**Comment by svenmarley** [comment]
Note also - you can easily replicate the case sensitivity here as well.

1. Set log to  "info; My*=debug"  - only info and errors come out
2. Set log to "info; my*=debug"   - and all error types come out

This shows that the value must be case sensitive to the name of the channel.

**Comment by Download** [comment]
@svenmarley Yes, that is expected behavior

**Comment by Download** [comment]
@reinhard 
Mmm so I guess the problem is that the log statements that are in function `App` don't respect the settings?
Maybe it is a timing issue. Thanks for this repro!

**Comment by Download** [comment]
@reinhard I confirmed your issue and split it off into #50
I will try to fix this for the next beta.
Thank you for the detailed repro! This is exactly the kind of feedback I need to make sure that v2 will work for everyone everywhere.

**Comment by Download** [comment]
@svenmarley Can you let me know if you still have issues that are not covered by #56 ?
Otherwise I'd like to close this issue as it's getting big but I don't see anything actionable left for me here.

**Comment by svenmarley** [comment]
I have no other issues outstanding.  I had misunderstood that the log entries are supposed to be case-sensitive.  Everything is working great on my side.  Thanks.
