### ISSUE TITLE
log no longer maps to the console object? log.dir broken?

### ISSUE THREAD

**Issue by abhi7214** [Download/ulog#67]
In 2.0.0 beta 13, a call to log.dir() used to map to console.dir() in Chrome.

In beta 14 thru 18 this functionality is broken, and I see an error in Chrome's console that says log.dir() is not a valid function. Will this functionality be restored? Or is there a better way to move forward?

**Comment by Download** [comment]
Yes you are right. I scrapped `log.dir` because it's not used a lot, not compatible with the [anylogger api])(https://github.com/download/anylogger/#anylogger-api) and very specific to the console. `ulog` wants to support other outputs as well and `console.dir` is difficult in that respect.

> Will this functionality be restored? 

Not likely. Not in the base package anyway. `ulog` targets some pretty ambitious goals and a small footprint is one of them, so I removed everything that could possibly be removed, moved it into mods and made a very strict selection on which mods would be in the base package.

> Or is there a better way to move forward?

What you can do is bring it back through a mod. Eventually I would probably build it myself, but that might be far in the future... 

If you are interested I can help you build such a mod and I can publish it along with all other mods in the `ulog` repo. Or you could make your own repo if you feel that would be better. If you do make such a mod and contribute it I will reward you with Collaborator access to the `ulog` repo and a mention in the credits section of the README.

If you want to try this out, I suggest forking this repo to your own account, cloning your own fork to your workspace, making a branch (suggested name: `feat/log-dir`), adding a folder for your mod below `mods/`, committing and pushing that and creating a PR from that branch. We can then collaborate on that feature in that PR.

**Comment by abhi137** [comment]
Let me switch to my personal account here. 

Yes, I would love to contribute but need your guidance on what all the mod should handle. I will also need to create a simple test development environment for this project. I presume I can start with a simple redirection to console if the object is available? Or I can look at the changes in beta 13 to see what all was removed and handle it more generically?

Happy to discuss more one on one if helpful.

**Comment by abhi137** [comment]
I was experimenting, but unable to find the right mod example to create a function on the logger object. Let me know if I am on the right track - 

ulog.use({
        extend: {
          dir: function(obj) {
            // Improve later to ensure console exists, and in browser. 
            console.dir(obj); 
          }
        }
      });

// This works, but not intended.
ulog.dir({ a: 2 })

// This is the ideal end state ... but this does not work via the above.
anylogger(logger).dir({a: 'c'});

I'd also like to create another function along the lines of -
- function dir2(level, object) - which only prints the object if the level passed is being logged.

**Comment by Download** [comment]
Ah yes. `extend` extends the `ulog` function itself.

To create an extra log function on all created loggers, you would have to use the hook function `ext`: 

```js
ulog.use({
  ext: function(logger) {
    // cheap and dirty
    logger.dir = console.dir
  }
})
```

Now if you do this, your `logger.dir` function will be special. It will not cooperate in the big stuff that `ulog` enables on the other log functions such as coloring, formatting, aligning etc. But maybe that's good since `console.dir` *is* special?

If you want `logger.dir` to work with all those fancy features that are available for the other log functions, you should have a look at how `logger.info` etc are created. Have a look at [mods/channels](https://github.com/Download/ulog/blob/master/mods/channels/index.js#L36):

```js
// enhance the given loggers with channels
  ext: function(logger) {
    var ulog = this
    var channels = grab(ulog, 'channels', {})
    var channelOutputs = grab(ulog, 'channelOutput', [])
    var recorders = grab(ulog, 'record', [])
    logger.channels = {}
    for (var channel in channels) {
      var ch = logger.channels[channel] = {
        name: channel,
        channels: channels,
        out: channels[channel].out || console,
        recorders: recorders,
        fns: {},
      }
      ch.out = channelOutputs.reduce(function(r, channelOutput){
        return channelOutput.call(ulog, logger, ch) || r
      }, ch.out);
      for (var level in ulog.levels) {
        var rec = ch.recorders.reduce(function(rec, record){
          record.call(ulog, logger, rec)
          return rec
        }, { channel: channel, level: level })
        ch.fns[level] = (function(ch,rec){
          return (typeof ch.out == 'function'
            ? function(){
              rec.message = [].slice.call(arguments)
              ch.out(rec)
            }
            : method(ch.out, rec)
          )
        })(ch,rec)
      }
    }
  },
```

That `for (var level in ulog.levels){  /* .. */ }` loop is the place where the logger functions are created and assigned to `ch.fns[level]`. Then later on, after the other mods have had the chance to do things to these functions (override them, wrap them, whatever), it assigns these channel functions to the logger:

```js
  // after all ext hooks have run, assign the log methods to
  // the right channels based on logger.enabledFor
  after: function(logger) {
    for (var level in this.levels) {
      logger[level] = logger.channels[logger.enabledFor(level) ? 'output' : 'drain'].fns[level]
    }
  },
```

Notice how it picks the `output` or `drain` channel based on whether the logger is enabled?

You would somehow have to make sure that both these loops run for all the levels as well as for your console.dir function. That might mean making some hook that by default returns `ulog.levels` but could also return something else. Looking at the code in the `channels` mod, I think that probably it was not a good idea of mine to hardcoded loop over `this.levels`. I shouls have made it so that it called a hook function named `methods` or something... 

Now before I can give good recommendations about which type of solution to build, it would maybe be good if you explain to me why you want to call `console.dir`? I mean the whole interactive part of it does not mesh well with logging right? Mostly we want to be able to log to e.g. a file. But what would the result of `logger.dir(myObject)` look like when logged to a file?

**Comment by abhi137** [comment]
I am using ulog for a Chrome extension for this specific project. It is an internal extension for my company, so it won't have public use/reference. I have 100s of "log.dir(object)" peppered through my code, and they are called like this - 

`if (log.level >= log.INFO) log.dir(jsObject)`

These stay disabled for production. During development or debugging, I am able to selectively enable these at a module level, and depending on the log level for that module, the right console.dirs get called.

Agree, console.dir is only for Chrome interactive. However, very useful for me since it is often better to dump the entire JS object rather than print each property one by one.

I recall it used to also work with node/npm in a terminal IIRC, it used to print a (static) tree like structure (1 level deep). Not too fancy but workable. Not sure if that is ulog functionality or nodejs functionality. Another option is to do pretty print in JSON format, but some would consider that an overkill.

Worst case, I will have to change 'log.dir' above to 'console.dir' as I go along.

I think the key here is - what is the best mode/option for Chrome extension developers, and I am just happy to follow your advice.

**Comment by Download** [comment]
Ok I understand. I guess the simplest solution would be to just add the `dir` function via a mod that you add in your entry point. 

> // Improve later to ensure console exists, and in browser.

You can use [the console channel](https://github.com/Download/ulog/blob/master/mods/channels/console.js) in `ulog` to not have to directly deal with the native `console`. 

*index.js*

```js
import ulog from 'ulog'
import console from 'ulog/mods/channels/console'
ulog.use({
  ext: function(logger){
    // bring back the `logger.dir()` method
    logger.dir = console && (console.dir || console.log) || function(){}
  }
})
```

**Comment by Download** [comment]
@abhi137 Feel free to re-open if you want to continue the discussion

**Comment by abhi137** [comment]
@Download - I noticed over the weekend that log.log(jsObject) just works and shows the object in Chrome (in an interactive way). This is exactly what I was looking for.

If I set the log level higher, it also automatically hides those from logging.

**Comment by Download** [comment]
@abhi137 

> I noticed over the weekend that log.log(jsObject) just works

Yes, I think it effectively translates to `log.log(''%o`, jsObject)`. 

> I missed an opportunity to contribute!

Never! 😉 

If you still like to try to make a mod for this, I'm still willing to support you and add it to this repo.

**Comment by abhi137** [comment]
On this one, let’s stay with the existing functionality; log.log works great. I will think of a better mod based on my usage.

Abhi.
